name: Test with pytest

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    types: ["opened", "reopened"]

jobs:
  pytest:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install '.[test]'
    - name: Test with pytest
      run: |
        pytest